### ISSUE TITLE
The scrollview does not update correct after replacing the text content

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#101]
After setting a string in the CPTextViews textStorage the scrolling area is not updated. 

The code used is:
``` [storage replaceCharactersInRange:aRange withAttributedString:aString]; ```

So if the text is larger than the view it is only possible to scroll down after inserting text direct into the view. 
Or if the text is less than it was previously it is possible to scroll to the same size as the old text  had.

**Comment by daboe01** [comment]
@kerusan did you surround your code with  [storage beginEditing] and [storage endEditing]?
does this fix your issue?

**Comment by kerusan** [comment]
No it does not fix the issue.

**Comment by daboe01** [comment]
@kerusan does 048e30c9890bb189f35941ecd213b36eec21aeab fix your issue (with beginEditing and endEditing in place)?

**Comment by kerusan** [comment]
Sorry, it does not. It must be something deeper.
Should not the beginEditing/endEditing be used only when you group multiple changes? I have a cocoa app that mimics my cappuccino app and its not needed there. I looked at your demo of CPTextView but it did not have any scrollbars so I cant verify the problem there.

**Comment by kerusan** [comment]
I am setting a rather big text into the textview. Attaching the text here.
[xxx.rtf.zip](https://github.com/daboe01/CPTextView/files/306243/xxx.rtf.zip)

**Comment by daboe01** [comment]
The NSMutableAttributedString implementation does nothing. NSTextStorage, for example, overrides this method to invoke fixAttributesInRange: and to _inform its NSLayoutManager objects that they need to re-lay the text._ (from https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSMutableAttributedString_Class/index.html#//apple_ref/occ/instm/NSMutableAttributedString/endEditing)

**Comment by daboe01** [comment]
@kerusan i will try looking at your issue this evening.

**Comment by kerusan** [comment]
Ok thanx.

here is the code I am currently using to set the text in the view.

```
- (void)makeEditable:(BOOL)flag {
    //CPLog.trace("[" + [self class] + " " + _cmd + "] ");

    isEditable = flag;
    [contentTextView setEditable:flag];
    [nameTextField setEditable:flag];
    [languageTextField setEditable:flag];
    if (flag) {
        [contentTextView setTextColor:[CPColor blackColor]];
    } else {
        [contentTextView setTextColor:[CPColor grayColor]];
    }
}

- (void)placeTextInView:(CPString)aText {
    //CPLog.trace("[" + [self class] + " " + _cmd + "] ");

    var storage = [contentTextView textStorage];
    var outputLength = [storage length];
    var newOutput = [[CPAttributedString alloc] initWithString:aText];
    var outputRange = CPMakeRange(0,outputLength);
    var terminalFont = [CPFont fontWithName:@"Courier" size:14];
    //
    [contentTextView setFont:terminalFont];
    [storage beginEditing];
    [storage replaceCharactersInRange:outputRange withAttributedString:newOutput];
    [[contentTextView textContainer] setWidthTracksTextView:YES];
    [storage endEditing];

    [self makeEditable:[contentTextView isEditable]];
}
````

**Comment by daboe01** [comment]
it was a missing sizeToFit.
should be fixed now

**Comment by daboe01** [comment]
@kerusan does this work for you?

**Comment by kerusan** [comment]
Yes it works now, thank you Daniel.
