### ISSUE TITLE
regression: _CPNativeInputManager does not get focus in Safari (not Chrome)

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#102]
When backspace'ing to remove the last edited character in the textview, two characters gets removed from the line. This error occurs in the browser Safari on MacOSX, in Chrome it deletes correct (only one character).

**Comment by daboe01** [comment]
i do not see this here (version 9.1, 11601.5.17.1).
could you please give more details to reproduce?

**Comment by daboe01** [comment]
ok, i see it also on Version 9.1.1 (11601.6.17).
they seem to have changed something with the latest update.

**Comment by daboe01** [comment]
the issue is that for some reasons, the contenteditable div _CPNativeInputField does not get the focus in the latest safari.
this breaks all sorts of things.

**Comment by daboe01** [comment]
fixed.
