### ISSUE TITLE
Selecting text with doubleClick selects to few characters 

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#108]
Selecting the red color Fusce using double click on the character s works in Chrome, but in Safari, Firefox and Opera only the lowercase letters gets selected.

<img width="200" alt="skarmavbild 2016-06-17 kl 16 06 31" src="https://cloud.githubusercontent.com/assets/783541/16153181/85294694-34a5-11e6-8f96-7827f2fb856c.png">

**Comment by daboe01** [comment]
@kerusan this particular example is an edge case from trying to select the very first character.
do you also see this in other locations?

**Comment by daboe01** [comment]
i think i fixed it.
@kerusan can you please report if you still see issues?
