### ISSUE TITLE
Colored text is not pasted as original text

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#111]
When copying text with more than two colors, the text is not pasted right.
See pics.
![skarmavbild 2016-06-23 kl 11 37 37](https://cloud.githubusercontent.com/assets/783541/16298862/b9b36656-3937-11e6-999a-d62fd24dbc11.png)
![skarmavbild 2016-06-23 kl 11 46 29](https://cloud.githubusercontent.com/assets/783541/16298975/2f519eaa-3938-11e6-86af-f99613198717.png)

**Comment by daboe01** [comment]
Can you paste the RTF into TextEdit? If the colors show up correct there, we have to look only at the parser. Otherwise we need to only check the RTF generator code.

**Comment by daboe01** [comment]
the bug seems to be in the producer.

**Comment by kerusan** [comment]
Works! Thanx for fixing!
