### ISSUE TITLE
proper baseline-alignment

### ISSUE THREAD

**Issue by daboe01** [daboe01/CPTextView#21]
(hint: collect heights in the same way as the advancements)

**Comment by aparajita** [comment]
This is critical, currently baselines are not aligned if text is of different sizes on the same line. See [this code](https://github.com/aparajita/SCKit/blob/master/SCUtils.j) for some possible approaches to aligning baselines.

**Comment by daboe01** [comment]
this has a low priority for me.
nobody usually really wants to mix different font sizes on the same line.

**Comment by aparajita** [comment]
> nobody usually really wants to mix different font sizes on the same line

Maybe, we'll see.

**Comment by daboe01** [comment]
i just took a deeper look into this.
basic support is there as of my latest commit.
 uncomment line 244 in CPLayoutManager to activate it.

proper baseline alignment is has a long way to go, though.
* multiple line fragments per line (as introduced by tabstops or justified text) currently do not work properly work with baseline alignment in some circumstances
* keyboard movements (i.e. up/down) will not work with baseline alignment in some circumstances
* selection and caret sizes are somehow weird with baseline alignment in some circumstances

**Comment by daboe01** [comment]
easier than i thought :-)
fixed.
