### ISSUE TITLE
Style is inherited from previous character

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#52]
The style seems to be inherited from the previous characters when inserting or changing a selection.
I can't see this behavior in Cocoa.
To reproduce this just position the caret to the second line in the demo view. Or select the first word on the second line and start typing. The characters becomes red.

**Comment by daboe01** [comment]
thank you!
i fixed both here and in PR.
i will update the demo as soon as possible.

**Comment by daboe01** [comment]
demo updated.

**Comment by kerusan** [comment]
Cool now it works like TextEdit!
