### ISSUE TITLE
Stray pixel at bottom of caret during dead key entry

### ISSUE THREAD

**Issue by aparajita** [daboe01/CPTextView#66]
When entering a dead key, the CPTextView caret is not completely erased before the native caret appears, and this can leave a stray pixel at the bottom if the CPTextView caret is longer than the native caret.

**Comment by daboe01** [comment]
i do not see this here.
which font size?
which browser?

**Comment by daboe01** [comment]
the textview caret is a div. this can only be removed or displayed in total.
i do not see how we can get stray pixels in this approach.

**Comment by aparajita** [comment]
Using Safari, with 18 pt text. You may have to magnify the screen to see the stray pixel. You can see it in this screen shot, at the lower right corner of the yellow input box.
![cptextview](https://cloud.githubusercontent.com/assets/22218/8030316/962d045c-0dce-11e5-82e7-bbbb2be8ad35.png)

**Comment by daboe01** [comment]
this is what i am seeing in safari:
![bildschirmfoto 2015-06-08 um 20 28 03](https://cloud.githubusercontent.com/assets/146335/8042077/e99d6aac-0e1c-11e5-8929-e77c2adcad05.PNG)

**Comment by daboe01** [comment]
maybe this is because of my recent commits. do you still see it?

**Comment by aparajita** [comment]
No.
