### ISSUE TITLE
Color in font panel not set

### ISSUE THREAD

**Issue by aparajita** [daboe01/CPTextView#67]
If colored text is selected and the font panel is opened, the color swatch does not reflect the color of the text.

**Comment by daboe01** [comment]
i do not see this here.
are you referring to a non-zero length selection?

![bildschirmfoto 2015-06-05 um 14 13 28](https://cloud.githubusercontent.com/assets/146335/8005681/246f061e-0b8d-11e5-8c8e-a39023d3f14f.PNG)

**Comment by aparajita** [comment]
I narrowed down the bug. If a string of characters is colored, and the **first** character of the string is selected -- whether or not following characters are as well -- then the color swatch is black.

For example, select "neque" on the first line, set it to a color, then select "ne", and the color swatch is black, whereas selecting "eq" correctly sets the color swatch.

**Comment by daboe01** [comment]
fixed
