### ISSUE TITLE
Dead key input element leaves margin on right

### ISSUE THREAD

**Issue by aparajita** [daboe01/CPTextView#71]
When entering a dead key in between existing characters, there is extra space to the right of the dead key input element. See the attached screenshot:

![cptextview](https://cloud.githubusercontent.com/assets/22218/8030348/d742e4fc-0dce-11e5-937c-8bb77e4164c2.png)

Same thing in google docs:

![google docs](https://cloud.githubusercontent.com/assets/22218/8030407/5663550a-0dcf-11e5-86f1-e3ef767c7617.png)

**Comment by daboe01** [comment]
thanks, fixed
