### ISSUE TITLE
Pressing Command aborts dead key entry

### ISSUE THREAD

**Issue by aparajita** [daboe01/CPTextView#72]
If you press a dead key and then press Command (on OS X), dead key entry is aborted. Obviously it shouldn't be if only the Command key is pressed.

**Comment by daboe01** [comment]
i have no idea how to fix this robustly.
Unlike Shift/Alt/Ctrl, Mac/Apple key is not considered as a modifier key
<http://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript>

**Comment by daboe01** [comment]
i should add that event.metaKey is already false in the keyup handler when you release the command key (at least on chrome)

**Comment by daboe01** [comment]
this does not happen in FF.
the webkit-command keys 92 and 93 should be the same in all mac keyboard-layouts.
do you think filtering them out is ok?

**Comment by daboe01** [comment]
i fixed this with the scan codes. this works well in my testing
