### ISSUE TITLE
Pressing delete during dead key entry leaves blank space

### ISSUE THREAD

**Issue by aparajita** [daboe01/CPTextView#75]
If you place the caret within existing text, press a dead key, then delete, the native input element is removed, but an empty space the size of the native input element remains.

**Comment by daboe01** [comment]
thank you. fixed

**Comment by aparajita** [comment]
Broken in Safari. When you press delete after a dead key, `<br>` appears.

**Comment by daboe01** [comment]
thank you for testing in safari. fixed.
