### ISSUE TITLE
Position of the texts moves when hitting enter at the end of a line

### ISSUE THREAD

**Issue by daboe01** [daboe01/CPTextView#83]
![](https://cloud.githubusercontent.com/assets/2860781/10112117/93f84dda-638d-11e5-8a9c-1784bcbc5e16.gif)

**Comment by daboe01** [comment]
@Dogild i do not see this here?
is this possibly a dupicate of the font issue you see with xcode?

**Comment by Dogild** [comment]
Not sure ! Did you try with the cib test ?

(Not home to try right now)

Envoyé de mon iPhone

**Comment by Dogild** [comment]
This one is fixed !
