### ISSUE TITLE
CPTextView setSelectable:YES sets isEditable to YES 

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#94]
When the method `setSelectable:` is set to YES it also sets the `isEditable` to YES. This is not what NSTextView do. It should be if `setSelectable:`is set to NO then it should not be editable.
See:
```
- (void)setSelectable:(BOOL)flag
{
    [self willChangeValueForKey:"selectable"]
    _isSelectable = flag;
    if (flag)
        _isEditable = flag;
    [self didChangeValueForKey:"selectable"]
}
```
From the AppKit reference for 'selectable' property
**Discussion**
If YES, the receiver is made selectable but not editable (use editable to make text both selectable and editable). If NO, the text is neither editable nor selectable.

**Comment by kerusan** [comment]
What exactly are supposed to happen when calling setEditable:NO. Right now I don't see any difference.

**Comment by daboe01** [comment]
@kerusan thank you, fixed.
