### ISSUE TITLE
CPTextView's text does not change width horizontally when text view is resized

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#95]
If the CPTextView is put in a scroll view the vertically scrollbar works perfectly but the horizontally scroller is not present (even if the view is made smaller) and the text is wrapped at a fixed width (actually the width that the view has in InterfaceBuilder). 
Also the text lines does not seems to resize from the text views initial width when the scroll view is resized.
It probably does not listen to the resize of the surrounding view.
This behaviour occurs when the text view's rubber band in InterfaceBuilder are set to resize and the view is fixed to the scrollview.
This behaviour occurs in all major browsers.

**Comment by daboe01** [comment]
@kerusan thank you for reporting this. i have not seen this i do not use interface builder. resizing works perfectly when set up in code. Could you please try sending
```Objective-J
[[myTextView textContainer] setWidthTracksTextView:YES];
```
and report back whether this fixes your problem?

**Comment by kerusan** [comment]
Yes it does.
First I calledl your line every time I called setString:, but it works by setting it only one time.
 
I tried first to set maxWidth to something big, but that did not help. 
Thanx.

**Comment by daboe01** [comment]
@kerusan i hope that https://github.com/daboe01/cappuccino/commit/7acb30b981c193361be1ebf55468ee9f93aac79c fixes you issue.
can you confirm please?

**Comment by kerusan** [comment]
It does!
