### ISSUE TITLE
Setting textColor only changes first lines color

### ISSUE THREAD

**Issue by kerusan** [daboe01/CPTextView#96]
When changing the text-color from code with the message 
```        [myTextView setTextColor:[CPColor greyColor]]; ```
will only change the color on the first line.

**Comment by daboe01** [comment]
fixed

**Comment by kerusan** [comment]
This issue seems to be back again.

**Comment by daboe01** [comment]
thank you for reporting. i will check as soon as possible.

**Comment by daboe01** [comment]
fixed

**Comment by daboe01** [comment]
fixing this is harder than i thought :-(
