### ISSUE TITLE
missing: support for native rich paste as in google docs

### ISSUE THREAD

**Issue by daboe01** [daboe01/CPTextView#98]

**Comment by daboe01** [comment]
we may have to take a look at this:
https://github.com/nicolasgoutaland/GONMarkupParser
and this:
https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md

**Comment by daboe01** [comment]
this one may come in handy

http://stackoverflow.com/questions/21257688/paste-rich-text-into-content-editable-div-and-only-keep-bold-and-italics-formatt

**Comment by daboe01** [comment]
this one is really exciting:
http://ejohn.org/blog/pure-javascript-html-parser/

**Comment by kerusan** [comment]
Looks really interesting! Maybe it can be wraped into a CPXMLParser :-)

**Comment by daboe01** [comment]
for copy: i think it is best to temporarily enforce a browser selection on the textfield dom during the native event.. this will hopefully put a rich representation on the system clipboard.
for paste: we will probably iterate the dom below the hidden contenteditable div that is accepting the paste and build an attributedString. this has to be done after the native paste event. the attributedString can then be inserted into the textField.

**Comment by daboe01** [comment]
i just learned the hard way that it is not possible to copy rich text and paste it into a native app that accepts rich text. even google docs does not support this.

**Comment by daboe01** [comment]
got it working in chrome in the rich-paste branch .
only color at the moment :-(
maybe someone is willing to help finishing this?
anyone interesting in testing?
![bildschirmfoto 2016-07-17 um 09 09 56](https://cloud.githubusercontent.com/assets/146335/16899275/87acc88a-4bfe-11e6-910d-dc3c99f46aac.PNG)

**Comment by daboe01** [comment]
safari support for rich pasting really sucks at the moment.

is anybody already on sierra? i would love to see if safari will eventually put html or preferably rtf on the browser pasteboard. you can see the types put on the pasteboard here: http://codebits.glennjones.net/editing/getclipboarddata.htm

**Comment by daboe01** [comment]
working 100% with FF.
chrome: only color support for now.
safari: not supported because i do not get the paste event bubble.
anyone any ideas on this?
closing this for now because the basic framework is there.
